/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import config.dbConnector;
import java.awt.BasicStroke;
import java.awt.Color;
import static java.awt.Frame.ICONIFIED;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Vilma Gaming
 */

public class userPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form userPage
     */
    public userPage() {
        initComponents();
        
        displayData();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        search.setOpaque(false);
        search.setBackground(new Color(0,0,0,0));
        
    }
    
    public void displayData(){
      try{
          dbConnector dbc = new dbConnector();
          ResultSet rs = dbc .getData("SELECT * FROM tbl_user");
          pet_table.setModel(DbUtils.resultSetToTableModel(rs));
            
      }catch(SQLException ex){
         System.out.println("Errors:"+ex.getMessage());
    }
       
}
    
    
    
       Color narv = new Color(0,102,102);
       Color head = new Color(0,153,153);
       Color body = new Color(0,153,153);
    
   
       public String gender;
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pet_table = new javax.swing.JTable();
        ADD = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        EDIT = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        DLT = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        srch = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        REF = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(760, 420));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(580, 0, 110, 50);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel2.setText("ADOPTION");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 0, 330, 50);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jScrollPane1.setViewportView(pet_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 700, 260));

        ADD.setBackground(new java.awt.Color(0, 153, 153));
        ADD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD");

        javax.swing.GroupLayout ADDLayout = new javax.swing.GroupLayout(ADD);
        ADD.setLayout(ADDLayout);
        ADDLayout.setHorizontalGroup(
            ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ADDLayout.setVerticalGroup(
            ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 30));

        EDIT.setBackground(new java.awt.Color(0, 153, 153));
        EDIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EDIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EDITMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EDITMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EDIT");

        javax.swing.GroupLayout EDITLayout = new javax.swing.GroupLayout(EDIT);
        EDIT.setLayout(EDITLayout);
        EDITLayout.setHorizontalGroup(
            EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDITLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EDITLayout.setVerticalGroup(
            EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(EDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 60, 30));

        DLT.setBackground(new java.awt.Color(0, 153, 153));
        DLT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DLTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DLTMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DELETE");

        javax.swing.GroupLayout DLTLayout = new javax.swing.GroupLayout(DLT);
        DLT.setLayout(DLTLayout);
        DLTLayout.setHorizontalGroup(
            DLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DLTLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DLTLayout.setVerticalGroup(
            DLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(DLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, 30));

        search.setBackground(new java.awt.Color(0, 153, 153));
        search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 140, 30));

        srch.setBackground(new java.awt.Color(0, 153, 153));
        srch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        srch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                srchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                srchMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SEARCH");

        javax.swing.GroupLayout srchLayout = new javax.swing.GroupLayout(srch);
        srch.setLayout(srchLayout);
        srchLayout.setHorizontalGroup(
            srchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(srchLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        srchLayout.setVerticalGroup(
            srchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 60, 30));

        REF.setBackground(new java.awt.Color(0, 153, 153));
        REF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        REF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REFMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("REFRESH");

        javax.swing.GroupLayout REFLayout = new javax.swing.GroupLayout(REF);
        REF.setLayout(REFLayout);
        REFLayout.setHorizontalGroup(
            REFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REFLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        REFLayout.setVerticalGroup(
            REFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(REF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        ADD.setBackground(narv);      
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
       ADD.setBackground(head); 
    }//GEN-LAST:event_ADDMouseExited

    private void EDITMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITMouseEntered
        EDIT.setBackground(narv); 
    }//GEN-LAST:event_EDITMouseEntered

    private void EDITMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITMouseExited
        EDIT.setBackground(head); 
    }//GEN-LAST:event_EDITMouseExited

    private void DLTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLTMouseEntered
        DLT.setBackground(narv); 
    }//GEN-LAST:event_DLTMouseEntered

    private void DLTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLTMouseExited
        DLT.setBackground(head); 
    }//GEN-LAST:event_DLTMouseExited

    private void srchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srchMouseEntered
        srch.setBackground(narv); 
    }//GEN-LAST:event_srchMouseEntered

    private void srchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srchMouseExited
        srch.setBackground(head); 
    }//GEN-LAST:event_srchMouseExited

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
       JFrame mainFrame = (JFrame)SwingUtilities.getWindowAncestor(this);
       mainFrame.dispose();
        Aform af = new Aform();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADDMouseClicked

    private void REFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFMouseEntered
        REF.setBackground(narv);
    }//GEN-LAST:event_REFMouseEntered

    private void REFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFMouseExited
        REF.setBackground(head);
    }//GEN-LAST:event_REFMouseExited

    private void REFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFMouseClicked
        displayData();
    }//GEN-LAST:event_REFMouseClicked

    private void EDITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITMouseClicked
        int rowindex = pet_table.getSelectedRow();
        if(rowindex<0){
            JOptionPane.showMessageDialog(null, "Please Select an Item!");
        }else{
            TableModel model = pet_table.getModel();
            Aform af = new Aform();
            af.p_id.setText(""+model.getValueAt(rowindex, 0));
            af.a_fn.setText(""+model.getValueAt(rowindex, 1));
            af.a_em.setText(""+model.getValueAt(rowindex, 2));
            af.a_cont.setText(""+model.getValueAt(rowindex, 3));
            af.a_status.setSelectedItem(model.getValueAt(rowindex, 5));
            af.a_addrss.setText(model.getValueAt(rowindex, 6).toString());
            af.setVisible(true);
            JFrame mainFrame = (JFrame)SwingUtilities.getWindowAncestor(this);
            mainFrame.dispose();
        }
    }//GEN-LAST:event_EDITMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADD;
    private javax.swing.JPanel DLT;
    private javax.swing.JPanel EDIT;
    private javax.swing.JPanel REF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pet_table;
    private javax.swing.JTextField search;
    private javax.swing.JPanel srch;
    // End of variables declaration//GEN-END:variables



}   

    

